from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from prophecy.libs import typed_lit
from PPLN_MD_MATL_15.config.ConfigStore import *
from PPLN_MD_MATL_15.udfs.UDFs import *

def sql_MD_MATL(spark: SparkSession) -> DataFrame:
    out0 = spark.sql(
        f"""
    select
 '{Config.sourceSystem}'  AS SRC_SYS_CD,
f4101_adt.imlitm AS MATL_NUM,
TRIM (f4101_adt.imsrp6) AS MATL_TYPE_CD,
NULL AS BRND_CD,
TRIM (f4101_adt.imsrp2) AS FRANCHISE_CD,
NULL AS LCL_PLNG_SUB_FRAN_CD,
NULL AS PRCHSNG_VAL_KEY_CD,
NULL AS DEL_IND,
TRIM(f4101_adt.imprp2) AS MATL_GRP_CD,
NULL AS INDSTR_SECTR_CD,
TRIM (f4101_adt.imuom1) AS BASE_UOM_CD,
CAST (TRIM(f4101_adt.imsld)   AS decimal(18,4)) AS TOT_SHLF_LIF_DAYS_CNT,
NULL AS MIN_SHLF_RMN_LIF_DAYS_CNT,
TRIM(f4101_adt.imstkt) AS MATL_STS_CD,
NULL AS DSTN_CHN_STS_CD,
NULL AS NET_WT_MEAS,
trim(f4101_adt.imprp4) AS PROD_HIER_CD,
NULL AS PRCMT_QUAL_MGMT_IND,
TRIM (f4101_adt.imprp7) AS STRG_CONDS_CD,
NULL AS LBL_TEMP_RNG,
NULL AS TRSPN_GRP_CD,
TRIM (f4101_adt.imsrce) AS BTCH_MNG_IND,
TRIM (f4101_adt.imdraw) AS MATL_DOC_NUM,
TRIM (f4101_adt.imrvno) AS MATL_DOC_VERS_NUM,
TRIM(f4101_adt.imdsc1) AS MATL_SHRT_DESC,
NULL AS MMS_SURGERY_TYPE_CD,
NULL AS MMS_MATL_TYPE_CD,
NULL AS PRMRY_PLNT_CD,
NULL AS MMS_FIN_CLSN_CD,
NULL AS MMS_STERILIZATION_IND,
TRIM (f4101_adt.imaitm) AS MATL_CATLG_NUM,
NULL AS SRC_SECTR_CD,
NULL AS MATL_PARNT_CD,
TRIM (f4101_adt.imsrp1) AS MATL_SUB_TYPE_CD,
TRIM (f4101_adt.imglpt) AS FIN_HIER_BASE_CD,
NULL AS IMPLNT_INSTM_IND,
NULL AS MATL_MOD_CD,
TRIM (f4101_adt.imsrp0) AS KIT_IND,
NULL AS MMS_TEMP_SENS_IND,
NULL AS DIR_PART_MRKNG_CD,
TRIM(f4101_adt.imsrp8) AS MATL_CAT_GRP_CD,
TRIM(f4101_adt.imprp0) AS PLNG_HIER3_CD,
NULL AS MATL_SPEC_NUM,
NULL AS MATL_SPEC_VERS_NUM,
TRIM(f4101_adt.imuser) AS CHG_BY,
NULL AS DOC_CHG_NUM,
NULL AS CNTNR_REQ,
NULL AS OLD_MATL_NUM,
NULL AS GRS_WT,
NULL AS ORDR_UNIT_PUR_UOM,
NULL AS CHEM_CMPLI,
NULL AS CRT_BY,
NULL AS CRT_ON_DTTM,
NULL AS LBL_TYPE,
NULL AS LBL_FORM,
NULL AS EXTRNL_MATL_GRP,
NULL AS MAX_LVL,
TRIM(f4101_adt.imuwum) AS WT_UNIT,
NULL AS SIZE_DIM,
NULL AS PER_IN,
CASE
    WHEN LENGTH(F4101_ADT.imtday) = 6 THEN TO_TIMESTAMP(
      CONCAT(
        DATE_ADD(
          CAST(
            SUBSTRING(F4101_ADT.IMUPMJ + 1900000, 1, 4) AS DATE
          ),
          CAST(SUBSTRING(F4101_ADT.IMUPMJ, 4, 3) AS INT) -1
        ),
        \"\"\"\",
        F4101_ADT.imtday
      ),
      'yyyy-MM-ddHHmmss'
    )
    WHEN LENGTH(F4101_ADT.imtday) = 5 THEN TO_TIMESTAMP(
      CONCAT(
        DATE_ADD(
          CAST(
            SUBSTRING(F4101_ADT.IMUPMJ + 1900000, 1, 4) AS DATE
          ),
          CAST(SUBSTRING(F4101_ADT.IMUPMJ, 4, 3) AS INT) -1
        ),
        \"\"\"\",
        concat(0, F4101_ADT.imtday)
      ),
      'yyyy-MM-ddHHmmss'
    )
    ELSE TO_TIMESTAMP(
      DATE_ADD(
        CAST(SUBSTRING(F4101_ADT.IMUPMJ + 1900000, 1, 4) AS Date),
        CAST(SUBSTRING(F4101_ADT.IMUPMJ, 4, 3) as INT) -1
      )
    )
END AS LAST_CHG_DT_TIME_DTTM,
NULL AS MATL_GRP_PKGNG_MATL,
NULL AS MATL_EXTRNL,
NULL AS STRG_PCT,
NULL AS VAL_FROM_XPLNT_DTTM,
NULL AS VAL_FROM_XDC_DTTM,
NULL AS INDSTR_STD_DESC,
NULL AS RD_RUL_SLED,
NULL AS SER_LVL,
NULL AS MATL_HAZ_CD,
NULL AS VAR_ORDR_UNT,
NULL AS PKGNG_MATL_TYPE,
TRIM(f4101_adt.imuvm1) AS VOL_UNIT,
CAST(TRIM(f4101_adt.imvcud) AS DECIMAL(18,4))  AS VOL,
NULL AS BSC_MATL,
TRIM(f4101_adt.imlnty) AS DOC_TYPE,
NULL AS DOC_PG_FMT,
TRIM(f4101_adt.imprp1) AS EAN_UPC,
NULL AS EAN_CAT,
NULL AS MFR_BOOK_PART_NUM,
NULL AS DIR_SHP_FL,
NULL AS FIN_PLNT,
NULL AS MAIN_STRG_LOC,
NULL AS PCS_PER_SLS_UNT,
NULL AS PROD_LINE,
TRIM(f4101_adt.imprp6) AS MAKE_BUY_IN,
NULL AS STRT_PLNT,
NULL AS MATL_SHRT_DESC_UP_CASE,
TRIM(f0005_06.drdl01) AS MATL_TYPE_DESC,
NULL AS FRAN_CD_DESC,
NULL AS BASE_UOM_DESC,
NULL AS OBJ_NUM,
NULL AS TYPE_OF_MATERIAL,
NULL AS STERILE,
TRIM(f4101_adt.imsrp7) AS BRAVO_MINOR_CODE,
TRIM(f0005_07.drdl01) AS BRAVO_MINOR_CODE_DESC,
NULL AS NDL_SLS_TYPE,
NULL AS SUTURE_LENGTH_INCH,
NULL AS SER_TYPE,
NULL AS GTIN_VRNT,
TRIM(f0005_p2.drdl01) AS MATL_GRP_DESC,
NULL AS MATL_GRP_DESC_2,
f4101_adt.imitm AS SHRT_MATL_NUM,
NULL AS CMMDTY,
NULL AS NDL_COLOR,
NULL AS NDL_ALLOY,
NULL AS SUTURE_USP,
NULL AS EAN_UPC_HRMZD
FROM {Config.sourceDatabase}.f4101_adt f4101_adt
LEFT JOIN {Config.sourceDatabase}.f0005 f0005_06 
ON F4101_ADT.IMSRP6 = TRIM(f0005_06.DRKY) 
AND TRIM(f0005_06.DRSY) = '41'
AND f0005_06.DRRT = '06'
AND f0005_06._deleted_ = 'F'
LEFT JOIN {Config.sourceDatabase}.f0005 f0005_07 
ON F4101_ADT.IMSRP7 = TRIM(f0005_07.DRKY) 
AND TRIM(f0005_07.DRSY) = '41'
AND f0005_07.DRRT = '07'
AND f0005_07._deleted_ = 'F'
LEFT JOIN {Config.sourceDatabase}.f0005 f0005_p2
ON F4101_ADT.IMPRP2 = TRIM(f0005_p2.DRKY)
AND TRIM(f0005_p2.DRSY) = '41'
AND f0005_p2.DRRT = 'P2'
AND f0005_p2._deleted_ = 'F'
WHERE  f4101_adt._deleted_ = 'F'  
 
"""
    )

    return out0
