from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from prophecy.libs import typed_lit
from sap_md_mfg_order_hcs.config.ConfigStore import *
from sap_md_mfg_order_hcs.udfs.UDFs import *

def SELECT_FIELDS(spark: SparkSession, in0: DataFrame) -> DataFrame:
    return in0.select(
        col("SRC_SYS_CD"), 
        col("MFG_ORDR_TYP_CD"), 
        col("MFG_ORDR_NUM"), 
        col("CHG_DTTM"), 
        col("CRTD_DTTM"), 
        col("DEL_IND"), 
        col("OBJECT_NUMBER"), 
        col("PLNT_CD"), 
        col("ORDR_CAT"), 
        col("REF_ORDR_NUM"), 
        col("ENT_BY"), 
        col("LAST_CHG_BY"), 
        col("DESC"), 
        col("LONG_TEXT_EXISTS"), 
        col("CO_CD"), 
        col("BUSN_AREA"), 
        col("CNTL_AREA"), 
        col("COST_CLCT_KEY"), 
        col("ORDR_CRNCY"), 
        col("ORDR_STS"), 
        col("LAST_STS_CHG_DTTM"), 
        col("STS_REACHED_SO_FAR"), 
        col("PH_ORDR_RELS"), 
        col("PH_ORDR_CMPLT"), 
        col("PLAN_CMPLT_DTTM"), 
        col("PLAN_CLS_DTTM"), 
        col("RLSE_DTTM"), 
        col("TECH_CMPLT_DTTM"), 
        col("CLSE_DTTM"), 
        col("OBJ_ID"), 
        col("USG_OF_THE_COND_TBL"), 
        col("APPL"), 
        col("COST_SHT"), 
        col("OVHD_KEY"), 
        col("PRCSG_GRP"), 
        col("SEQ_NUM"), 
        col("APPLT"), 
        col("EST_TOT_COSTS_OF_ORDR"), 
        col("APPL_DTTM"), 
        col("WRK_STRT_DTTM"), 
        col("END_OF_WRK_DTTM"), 
        col("PRFT_CTR"), 
        col("WRK_BRKDWN_STRC_ELMNT"), 
        col("VAR_KEY"), 
        col("RSLTS_ANAL_KEY"), 
        col("REQ_CO_CD"), 
        col("ITM_NUM_IN_SLS_ORDR"), 
        col("PRDTN_PRCS"), 
        col("DAI_ETL_ID"), 
        col("DAI_CRT_DTTM"), 
        col("DAI_UPDT_DTTM"), 
        col("_l0_upt_"), 
        col("_l1_upt_"), 
        col("PRIM_KEY").alias("_pk_"), 
        col("_pk_md5_"), 
        col("L0_DELETED").alias("_deleted_"), 
        col("MFG_ORDR_STTS_CD")
    )
