- branchNamePattern: '(feature|bugfix)/.*'
  environment: 'PREDEV'
- jobNamePattern: '.*deploy-(.*)'
  environment: '$1'
- branchNamePattern: 'development'
  environment: 'DEV'
- branchNamePattern: 'beta'
  environment: 'BETA'
- branchNamePattern: 'pqa'
  environment: 'PQA'
- branchNamePattern: 'production'
  environment: 'PROD'
- branchNamePattern: 'qa'
  environment: 'QA'
- branchNamePattern: 'release/.*'
  environment: 'QA'

