- branchNamePattern: '(feature|bugfix)/.*'
  environment: 'PREDEV'
- jobNamePattern: '.*deploy-(.*)'
  environment: '$1'
- branchNamePattern: 'beta'
  environment: 'DEV'
- branchNamePattern: 'test'
  environment: 'test'
- branchNamePattern: 'pqa'
  environment: 'PQA'
- branchNamePattern: 'production'
  environment: 'PROD'
- branchNamePattern: 'qa'
  environment: 'QA'
