from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from prophecy.libs import typed_lit
from prophecy.transpiler import call_spark_fcn
from prophecy.transpiler.fixed_file_schema import *
from sap_md_doc_itm_incm_invc_hm2_bba_bbl_bbn_geu_mrs_po1_tai.config.ConfigStore import *
from sap_md_doc_itm_incm_invc_hm2_bba_bbl_bbn_geu_mrs_po1_tai.udfs.UDFs import *

def FIELDS_ORDER_REFORMAT(spark: SparkSession, NEW_FIELDS: DataFrame) -> DataFrame:
    return NEW_FIELDS.select(
        col("_pk_md5_"), 
        col("_l1_upt_"), 
        col("_l0_upt_"), 
        col("DAI_UPDT_DTTM"), 
        col("DAI_CRT_DTTM"), 
        col("DAI_ETL_ID"), 
        col("ITM_NUM"), 
        col("INTRNL_LIC_NUM"), 
        col("CMMDTY_REPRC_INVC_VERIF"), 
        col("DIFF_AMT"), 
        col("IN_FOR_DIFF_INVC"), 
        col("GRP_CHAR_FOR_INVC_VERIF"), 
        col("ORIG_INVC_ITM"), 
        col("BTCH_NUM"), 
        col("ITM_KEY_FOR_ESOA_MSG"), 
        col("CONT_ITM_CAT_PRCHSNG_DOC"), 
        col("CENT_CNTRC_ITM_NUM"), 
        col("CENT_CNTRC"), 
        col("ITM_NUM_PRIN_PRCH_AGMT"), 
        col("NUM_OF_PRIN_PRCH_AGMT"), 
        col("CASH_LDGR_EXP_REVN_ACCT"), 
        col("TAX_RDCTN_FOR_RETN"), 
        col("RETN_DUE_DTTM"), 
        col("RETN_IN_PCT"), 
        col("RETN_AMT_IN_DOC_CRNCY"), 
        col("CMPNT_RSN_IN_INVC"), 
        col("UPDT_MLT_ACCT_ASGNMT"), 
        col("NUM_BILL_LDNG_GOODS_RCPT"), 
        col("ACCT_NUM_OF_VEND_OR_CR"), 
        col("CLRNG_GR_IR_PSTNG_EXTRNL"), 
        col("STK_PSTNG_INCM_PREV_YR"), 
        col("STK_PSTNG_INCM_INVC_PREV"), 
        col("STK_PSTNG_LINE_INCM_INVC"), 
        col("COND_CNTR"), 
        col("STEP_NUM"), 
        col("IN_INVC_ITM_PRCS"), 
        col("CORR_IN"), 
        col("LINE_ITM_NOT_LIAB_DISC"), 
        col("ITM_TEXT"), 
        col("LINE_NUM_OF_SRVC"), 
        col("PKG_NUM_OF_SRVC"), 
        col("DSTN_TYPE_FOR_EMP_TAX"), 
        col("RGN"), 
        col("ACTV_CD_FOR_GRS_INCM_TAX"), 
        col("TYPE_OF_VEND_ERR"), 
        col("INVC_AMT_DOC_CRNCY_INVC"), 
        col("QTY_INVC_IN_INVC_PO_PRC"), 
        col("QTY_INVC_IN_INVC_PO_ORDR"), 
        col("MATL_RSPCT_OF_STK_IS_MNG"), 
        col("ITM_OF_REF_DOC"), 
        col("FISC_YR_OF_CUR_PER"), 
        col("DOC_NUM_REF_DOC"), 
        col("LIFO_FIFO_RLVNT"), 
        col("VAL_TOT_STK_PREV_PER"), 
        col("VAL_TOT_VALUT_STK"), 
        col("COND_TYPE"), 
        col("DELV_COST_SHR_ITM_VAL"), 
        col("IN_DOC_PSTD_PREV_PER"), 
        col("REF_DOC_NUM"), 
        col("PSTNG_STRNG_FOR_VAL"), 
        col("BLOK_RSN_ENHNC_FLD"), 
        col("BLOK_RSN_QUAL"), 
        col("BLOK_RSN_ITM_AMT"), 
        col("MAN_BLOK_RSN"), 
        col("BLOK_RSN_PROJ_BGT"), 
        col("BLOK_RSN_ORDR_PRC_QTY"), 
        col("BLOK_RSN_DT"), 
        col("BLOK_RSN_QTY"), 
        col("IN_SUBSQ_DR_CR"), 
        col("UPDT_PRCH_ORDR_DELV_COST"), 
        col("IN_UPDT_PRCH_ORDR_HIST"), 
        col("FNL_INVC_IN"), 
        col("VALUT_CLS"), 
        col("ACCT_ASGNMT_CAT"), 
        col("ITM_CAT_IN_PRCHSNG_DOC"), 
        col("BASE_UNIT_OF_MEAS"), 
        col("TOT_VALUT_STK_PREV_PER"), 
        col("TOT_VALUT_STK"), 
        col("ORDR_PRC_UNIT_PRCHSNG"), 
        col("QTY_PRCH_ORDR_PRC_UNIT"), 
        col("PRCH_ORDR_UNIT_OF_MEAS"), 
        col("QTY"), 
        col("TAX_JURIS"), 
        col("TAX_ON_SLS_PRCH_CD"), 
        col("DR_CR_IN"), 
        col("AMT_IN_DOC_CRNCY"), 
        col("PLNT"), 
        col("CO_CD"), 
        col("VALUT_TYPE"), 
        col("VALUT_AREA"), 
        col("MATL_NUM"), 
        col("SEQ_NUM_OF_ACCT_ASGNMT"), 
        col("ITM_NUM_OF_PRCHSNG_DOC"), 
        col("PRCHSNG_DOC_NUM"), 
        col("DOC_ITM_IN_INVC_DOC"), 
        col("FISC_YR"), 
        col("ACTG_DOC_NUM"), 
        col("SRC_SYS_CD"), 
        col("_deleted_"), 
        col("_pk_")
    )
