from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from prophecy.libs import typed_lit
from tbl_strct_MD_MATERIAL.config.ConfigStore import *
from tbl_strct_MD_MATERIAL.udfs.UDFs import *

def sql_MD_MATL_DSTN_CHN(spark: SparkSession, ) -> (DataFrame):
    df1 = spark.sql(
        "select \ncast('' as string) as SRC_SYS_CD,\ncast('' as string) as MATL_NUM,\ncast('' as string) as SL_ORG_NUM,\ncast('' as string) as DSTR_CHNL_CD,\ncast('' as string) as PROD_HIER_CD,\ncast('' as string) as DELV_PLNT_CD,\ncast('' as string) as MATL_SLS_CAT_GRP_CD,\ncast('' as string) as ACTG_GRP_CD,\ncast('' as string) as DSTN_CHN_STS_CD,\ncast('' as timestamp) as VLD_FROM_DTTM,\ncast('' as string) as ENTRP_DSTN_CHN_STS_CD,\ncast('' as string) as MATL_BASE_CD,\ncast('' as string) as VOL_REBT_GRP,\ncast('' as string) as MATL_PRC_GRP,\ncast('' as string) as MATL_GRP_1,\ncast('' as string) as MATL_GRP_2,\ncast('' as string) as MATL_GRP_3,\ncast('' as string) as MATL_GRP_4,\ncast('' as string) as MATL_GRP_5,\ncast('' as string) as PRC_REF_MATL,\ncast('' as string) as MDD_SALEABLE,\ncast('' as string) as PHARMA_SALEABLE,\ncast('' as string) as CNSMR_SALEABLE,\ncast('' as string) as COMMSN_GRP,\ncast('' as string) as RD_PRFL,\ncast('' as string) as CASH_DISC_IN,\ncast('' as string) as MATL_STATS_GRP,\ncast('' as string) as MATL_DSTN_CHN,\ncast('' as string) as DEL_IN,\ncast('' as decimal(18,4)) as MIN_ORDR_QTY,\ncast('' as decimal(18,4)) as MIN_DELV_QTY,\ncast('' as decimal(18,4)) as MIN_MTO_QTY,\ncast('' as decimal(18,4)) as DELV_UNIT,\ncast('' as string) as UOM_DELV_UNIT,\ncast('' as string) as SLS_UNIT,\ncast('' as string) as ASRTMNT_GRADE,\ncast('' as string) as EXTRNL_ASRTMNT_PRIR,\ncast('' as string) as LIST_PCDR_STR_ASRTMNT_CAT,\ncast('' as string) as LIST_PCDR_DC_ASRTMNT_CAT,\ncast('' as string) as LIST_FUNC_ASRTMNT_ACT,\ncast('' as timestamp) as STR_LIST_FROM_DTTM,\ncast('' as timestamp) as STR_LIST_TO_DTTM,\ncast('' as timestamp) as DC_LIST_FROM_DTTM,\ncast('' as timestamp) as DC_LIST_TO_DTTM,\ncast('' as timestamp) as STR_SOLD_FRM_DTTM,\ncast('' as timestamp) as STR_SOLD_TO_DTTM,\ncast('' as timestamp) as DC_SOLD_FRM_DTTM,\ncast('' as timestamp) as DC_SOLD_TO_DTTM,\ncast('' as string) as PROD_ATTR_ID_4,\ncast('' as string) as PROD_ATTR_ID_5,\ncast('' as string) as PROD_ATTR_ID_6,\ncast('' as string) as PROD_ATTR_ID_7,\ncast('' as string) as PROD_ATTR_ID_8,\ncast('' as string) as PROD_ATTR_ID_9,\ncast('' as string) as PROD_ATTR_ID_10,\ncast('' as string) as UOM_GRP,\ncast('' as decimal(18,4)) as MAX_DELV_QTY,\ncast('' as string) as RACKJOBBER_MATL,\ncast('' as string) as PRC_FIX_IN,\ncast('' as string) as VAR_SLS_UNIT_IN,\ncast('' as string) as MATL_CMPT_CHAR,\ncast('' as int) as MATL_SORT,\ncast('' as string) as PRC_BND_CAT,\ncast('' as string) as MATL_SLS_CAT_GRP_DESC,\ncast('' as int) as PROD_HIER_LVL_NUM,\ncast('' as string) as PROD_HIER_DESC,\ncast('' as string) as DSTN_CHN_STS_CD_DESC,\ncast('' as string) as BLOK_FOR_SLS_ORDR,\ncast('' as int) as DAI_ETL_ID,\ncast('' as timestamp) as DAI_CRT_DTTM,\ncast('' as timestamp) as DAI_UPDT_DTTM,\ncast('' as timestamp) as _l0_upt_,\n cast('' as timestamp) as _l1_upt_,\n cast('' as string) as _pk_md5_,\n cast('' as string) as _pk_ \n limit 0"
    )

    return df1
