from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from prophecy.libs import typed_lit
from tbl_strct_MD_MATERIAL.config.ConfigStore import *
from tbl_strct_MD_MATERIAL.udfs.UDFs import *

def sql_MD_MATL_MFG_ALLC(spark: SparkSession, ) -> (DataFrame):
    df1 = spark.sql(
        "select \ncast('' as String) as SRC_SYS_CD,\ncast('' as String) as RTG_TYPE_CD,\ncast('' as String) as RTG_GRP_CD,\ncast('' as String) as ALLC_NUM,\ncast('' as String) as ALLC_VERS_CNTR_NBR,\ncast('' as timestamp) as VLD_FROM_DTTM,\ncast('' as String) as CHG_NUM,\ncast('' as String) as DEL_IND,\ncast('' as String) as RTG_GRP_CNTR_NBR,\ncast('' as String) as RTG_SEQ_NUM,\ncast('' as String) as RTG_NODE_NUM,\ncast('' as String) as BOM_CAT_CD,\ncast('' as String) as BOM_NUM,\ncast('' as String) as ALT_BOM_NUM,\ncast('' as String) as BOM_ITM_NODE_NUM,\ncast('' as String) as PLNT_CD,\ncast('' as decimal(18,4)) as CMPNT_QTY,\ncast('' as String) as CMPNT_UOM_CD,\ncast('' as timestamp) as CRT_DTTM,\ncast('' as timestamp) as CHG_DTTM,\ncast('' as String) as BKFLUSH_IND,\ncast('' as String) as MATL_NUM,\ncast('' as String) as TECH_STS_FROM,\ncast('' as String) as IN_INACT_CHG,\ncast('' as String) as INTG_DIVSR_CUT_MEAS,\ncast('' as decimal(18,4)) as CUT_MEAS_1,\ncast('' as decimal(18,4)) as CUT_MEAS_2,\ncast('' as decimal(18,4)) as CUT_MEAS_3,\ncast('' as String) as UNIT_CUT_MEAS,\ncast('' as String) as USER_CRT_REC,\ncast('' as String) as NM_PRSN_CHG_OBJ,\ncast('' as String) as ORDR_LVL,\ncast('' as String) as ORDR_PATH,\ncast('' as String) as NUM_TASK_LIST_NODE,\ncast('' as String) as PLNT,\ncast('' as String) as SUB_OPR,\ncast('' as String) as PLNG_OBJ,\ncast('' as String) as LINE_TEXT_SOP,\ncast('' as String) as TYPE_RL,\ncast('' as String) as UNIT_TIME_INTV_BTWN_RL,\ncast('' as decimal(18,4)) as TIME_INTV_BTWN_RL,\ncast('' as decimal(18,4)) as AVG_CMPNT_QTY,\ncast('' as String) as ACCT_ASGNMT_CAT,\ncast('' as String) as IN_EXTRNL_PRCMT,\ncast('' as String) as IN_PRLM_ORDR,\ncast('' as String) as IN_3PTY_REQSN,\ncast('' as String) as BOM_CAT,\ncast('' as String) as BILL_MATL,\ncast('' as String) as ALT_BOM,\ncast('' as String) as PATH_EXPLD_BOM_TREE,\ncast('' as String) as STRG_LOC_STRG_RSRS,\ncast('' as String) as RLVNT_MATL_PLNG,\ncast('' as String) as PROD_FLOW_IN,\ncast('' as String) as MATL_PRVSN_IN,\ncast('' as String) as UNLD_PT,\ncast('' as String) as GOODS_RCPNT,\ncast('' as timestamp) as VLD_TO_DTTM,\ncast('' as String) as DEL_IN,\ncast('' as String) as RTG_VERS,\ncast('' as String) as SRC_RTG_VERS,\ncast('' as String) as TASK_LIST_VERS,\ncast('' as String) as BOM_VERSN,\ncast('' as String) as BOM_VERSN_W,\ncast('' as String) as LOGL_CMPNT,\ncast('' as int) as DAI_ETL_ID,\ncast('' as timestamp) as DAI_CRT_DTTM,\ncast('' as timestamp) as DAI_UPDT_DTTM,\ncast('' as timestamp) as _l0_upt_,\n cast('' as timestamp) as _l1_upt_,\n cast('' as string) as _pk_md5_,\n cast('' as string) as _pk_ \n limit 0"
    )

    return df1
