from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from prophecy.libs import typed_lit
from PPLN_MD_MATL_1.config.ConfigStore import *
from PPLN_MD_MATL_1.udfs.UDFs import *

def sql_MD_MATL(spark: SparkSession) -> DataFrame:
    out0 = spark.sql(
        f"""
    select
 '{Config.sourceSystem}'  AS SRC_SYS_CD,
MARA.MATNR AS MATL_NUM,
TRIM(MARA.MTART) AS MATL_TYPE_CD,
TRIM(MARA.BRAND_ID) AS BRND_CD,
TRIM(MARA.SPART) AS FRANCHISE_CD,
TRIM(MARA.LABOR) AS LCL_PLNG_SUB_FRAN_CD,
TRIM(MARA.EKWSL) AS PRCHSNG_VAL_KEY_CD,
TRIM(MARA.LVORM) AS DEL_IND,
TRIM(MARA.MATKL) AS MATL_GRP_CD,
TRIM(MARA.MBRSH) AS INDSTR_SECTR_CD,
TRIM(MARA.MEINS) AS BASE_UOM_CD,
CAST(TRIM(MARA.MHDHB) AS DECIMAL(18, 4)) AS TOT_SHLF_LIF_DAYS_CNT,
CAST(TRIM(MARA.MHDRZ) AS DECIMAL(18, 4)) AS MIN_SHLF_RMN_LIF_DAYS_CNT,
TRIM(MARA.MSTAE) AS MATL_STS_CD,
TRIM(MARA.MSTAV) AS DSTN_CHN_STS_CD,
CAST(TRIM(MARA.NTGEW) AS DECIMAL(18, 4)) AS NET_WT_MEAS,
TRIM(MARA.PRDHA) AS PROD_HIER_CD,
TRIM(MARA.QMPUR) AS PRCMT_QUAL_MGMT_IND,
TRIM(MARA.RAUBE) AS STRG_CONDS_CD,
TRIM(MARA.TEMPB) AS LBL_TEMP_RNG,
TRIM(MARA.TRAGR) AS TRSPN_GRP_CD,
TRIM(MARA.XCHPF) AS BTCH_MNG_IND,
TRIM(MARA.ZEINR) AS MATL_DOC_NUM,
TRIM(MARA.ZEIVR) AS MATL_DOC_VERS_NUM,
TRIM(MAKT.MAKTX) AS MATL_SHRT_DESC,
NULL AS MMS_SURGERY_TYPE_CD,
NULL AS MMS_MATL_TYPE_CD,
NULL AS PRMRY_PLNT_CD,
NULL AS MMS_FIN_CLSN_CD,
NULL AS MMS_STERILIZATION_IND,
NULL AS MATL_CATLG_NUM,
NULL AS SRC_SECTR_CD,
NULL AS MATL_PARNT_CD,
NULL AS MATL_SUB_TYPE_CD,
NULL AS FIN_HIER_BASE_CD,
NULL AS IMPLNT_INSTM_IND,
NULL AS MATL_MOD_CD,
NULL AS KIT_IND,
NULL AS MMS_TEMP_SENS_IND,
NULL AS DIR_PART_MRKNG_CD,
TRIM(MARA.MTPOS_MARA) AS MATL_CAT_GRP_CD,
NULL AS PLNG_HIER3_CD,
NULL AS MATL_SPEC_NUM,
NULL AS MATL_SPEC_VERS_NUM,
TRIM(MARA.AENAM) AS CHG_BY,
TRIM(MARA.AESZN) AS DOC_CHG_NUM,
TRIM(MARA.BEHVO) AS CNTNR_REQ,
TRIM(MARA.BISMT) AS OLD_MATL_NUM,
CAST(TRIM(MARA.BRGEW) AS DECIMAL(18, 4)) AS GRS_WT,
TRIM(MARA.BSTME) AS ORDR_UNIT_PUR_UOM,
NULL AS CHEM_CMPLI,
TRIM(MARA.ERNAM) AS CRT_BY,
CASE
        WHEN MARA.ERSDA = '00000000' THEN CAST(NULL AS TIMESTAMP)
        ELSE to_timestamp(MARA.ERSDA, 'yyyyMMdd')
    END AS CRT_ON_DTTM,
TRIM(MARA.ETIAR) AS LBL_TYPE,
TRIM(MARA.ETIFO) AS LBL_FORM,
TRIM(MARA.EXTWG) AS EXTRNL_MATL_GRP,
TRIM(MARA.FUELG) AS MAX_LVL,
TRIM(MARA.GEWEI) AS WT_UNIT,
TRIM(MARA.GROES) AS SIZE_DIM,
TRIM(MARA.IPRKZ) AS PER_IN,
CASE
        WHEN MARA.LAEDA = '00000000' THEN CAST(NULL AS TIMESTAMP)
        ELSE to_timestamp(MARA.LAEDA,'yyyyMMdd')
    END AS LAST_CHG_DT_TIME_DTTM,
TRIM(MARA.MAGRV) AS MATL_GRP_PKGNG_MATL,
NULL AS MATL_EXTRNL,
TRIM(MARA.MHDLP) AS STRG_PCT,
CASE
        WHEN MARA.MSTDE = '00000000' THEN CAST(NULL AS TIMESTAMP)
        ELSE to_timestamp(MARA.MSTDE, 'yyyyMMdd')
    END AS VAL_FROM_XPLNT_DTTM,
CASE
        WHEN MARA.MSTDV = '00000000' THEN CAST(NULL AS TIMESTAMP)
        ELSE to_timestamp(MARA.MSTDV, 'yyyyMMdd')
    END AS VAL_FROM_XDC_DTTM,
TRIM(MARA.NORMT) AS INDSTR_STD_DESC,
TRIM(MARA.RDMHD) AS RD_RUL_SLED,
TRIM(MARA.SERLV) AS SER_LVL,
TRIM(MARA.STOFF) AS MATL_HAZ_CD,
TRIM(MARA.VABME) AS VAR_ORDR_UNT,
TRIM(MARA.VHART) AS PKGNG_MATL_TYPE,
TRIM(MARA.VOLEH) AS VOL_UNIT,
CAST(TRIM(MARA.VOLUM) AS DECIMAL(18, 4)) AS VOL,
TRIM(MARA.WRKST) AS BSC_MATL,
TRIM(MARA.ZEIAR) AS DOC_TYPE,
TRIM(MARA.ZEIFO) AS DOC_PG_FMT,
TRIM(MARA.EAN11) AS EAN_UPC,
TRIM(MARA.NUMTP) AS EAN_CAT,
NULL AS MFR_BOOK_PART_NUM,
NULL AS DIR_SHP_FL,
NULL AS FIN_PLNT,
NULL AS MAIN_STRG_LOC,
NULL AS PCS_PER_SLS_UNT,
NULL AS PROD_LINE,
NULL AS MAKE_BUY_IN,
NULL AS STRT_PLNT,
NULL AS MATL_SHRT_DESC_UP_CASE,
NULL AS MATL_TYPE_DESC,
NULL AS FRAN_CD_DESC,
NULL AS BASE_UOM_DESC,
NULL AS OBJ_NUM,
NULL AS TYPE_OF_MATERIAL,
NULL AS STERILE,
NULL AS BRAVO_MINOR_CODE,
NULL AS BRAVO_MINOR_CODE_DESC,
NULL AS NDL_SLS_TYPE,
NULL AS SUTURE_LENGTH_INCH,
NULL AS SER_TYPE,
TRIM(MARA.GTIN_VARIANT) AS GTIN_VRNT,
NULL AS MATL_GRP_DESC,
NULL AS MATL_GRP_DESC_2,
'#' AS SHRT_MATL_NUM,
NULL AS CMMDTY,
NULL AS NDL_COLOR,
NULL AS NDL_ALLOY,
NULL AS SUTURE_USP,
CASE
  WHEN (LENGTH(TRIM(MARA.EAN11)) > 0 AND LENGTH(TRIM(MARA.EAN11)) < 14) THEN LPAD(TRIM(MARA.EAN11), 14, 0)
  ELSE TRIM(MARA.EAN11)
END AS EAN_UPC_HRMZD
FROM
  {Config.sourceDatabase}.MARA MARA
  LEFT JOIN {Config.sourceDatabase}.MAKT MAKT on MARA.matnr = MAKT.matnr
  and MAKT.spras = 'E' and MAKT._deleted_ = 'F' and MAKT.MANDT = '100'
WHERE MARA._deleted_ = 'F' and MARA.MANDT = '100'  
 
"""
    )

    return out0
