from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from prophecy.libs import typed_lit
from sap_md_mfg_order_atl_bbl_bbn_bwi_hm2_hmd_mbp_mrs_p01_svs.config.ConfigStore import *
from sap_md_mfg_order_atl_bbl_bbn_bwi_hm2_hmd_mbp_mrs_p01_svs.udfs.UDFs import *

def RENAME(spark: SparkSession, in0: DataFrame) -> (DataFrame):
    in0.createOrReplaceTempView("in0")
    df1 = spark.sql(
        "SELECT\r\nAUFNR AS AFKO_AUFNR,\r\nABARB AS AFKO_ABARB,\r\nAPLZT AS AFKO_APLZT,\r\nARSNR AS AFKO_ARSNR,\r\nARSPS AS AFKO_ARSPS,\r\nAUFLD AS AFKO_AUFLD,\r\nAUFPL AS AFKO_AUFPL,\r\nAUFPT AS AFKO_AUFPT,\r\nBEDID AS AFKO_BEDID,\r\nCUOBJ AS AFKO_CUOBJ,\r\nDISPO AS AFKO_DISPO,\r\nFEVOR AS AFKO_FEVOR,\r\nFHORI AS AFKO_FHORI,\r\nFREIZ AS AFKO_FREIZ,\r\nFTRMI AS AFKO_FTRMI,\r\nFTRMP AS AFKO_FTRMP,\r\nFTRMS AS AFKO_FTRMS,\r\nGAMNG AS AFKO_GAMNG,\r\nGASMG AS AFKO_GASMG,\r\nGETRI AS AFKO_GETRI,\r\nGEUZI AS AFKO_GEUZI,\r\nGLTPP AS AFKO_GLTPP,\r\nGLTPS AS AFKO_GLTPS,\r\nGLTRI AS AFKO_GLTRI,\r\nGLTRP AS AFKO_GLTRP,\r\nGLTRS AS AFKO_GLTRS,\r\nGLUPP AS AFKO_GLUPP,\r\nGLUPS AS AFKO_GLUPS,\r\nGLUZP AS AFKO_GLUZP,\r\nGLUZS AS AFKO_GLUZS,\r\nGMEIN AS AFKO_GMEIN,\r\nGSTPP AS AFKO_GSTPP,\r\nGSTPS AS AFKO_GSTPS,\r\nGSTRI AS AFKO_GSTRI,\r\nGSTRP AS AFKO_GSTRP,\r\nGSTRS AS AFKO_GSTRS,\r\nGSUPP AS AFKO_GSUPP,\r\nGSUPS AS AFKO_GSUPS,\r\nGSUZI AS AFKO_GSUZI,\r\nGSUZP AS AFKO_GSUZP,\r\nGSUZS AS AFKO_GSUZS,\r\nIASMG AS AFKO_IASMG,\r\nIGMNG AS AFKO_IGMNG,\r\nKLVARI AS AFKO_KLVARI,\r\nKLVARP AS AFKO_KLVARP,\r\nLKNOT AS AFKO_LKNOT,\r\nLODIV AS AFKO_LODIV,\r\nMZAEHL AS AFKO_MZAEHL,\r\nPAENR AS AFKO_PAENR,\r\nPDATV AS AFKO_PDATV,\r\nPLAUF AS AFKO_PLAUF,\r\nPLGRP AS AFKO_PLGRP,\r\nPLNAL AS AFKO_PLNAL,\r\nPLNAW AS AFKO_PLNAW,\r\nPLNBEZ AS AFKO_PLNBEZ,\r\nPLNME AS AFKO_PLNME,\r\nPLNNR AS AFKO_PLNNR,\r\nPLNTY AS AFKO_PLNTY,\r\nPLSVB AS AFKO_PLSVB,\r\nPLSVN AS AFKO_PLSVN,\r\nPRONR AS AFKO_PRONR,\r\nPRUEFLOS AS AFKO_PRUEFLOS,\r\nPVERW AS AFKO_PVERW,\r\nRKNOT AS AFKO_RKNOT,\r\nRMZHL AS AFKO_RMZHL,\r\nRSHID AS AFKO_RSHID,\r\nRSNID AS AFKO_RSNID,\r\nRSNUM AS AFKO_RSNUM,\r\nRUECK AS AFKO_RUECK,\r\nSAENR AS AFKO_SAENR,\r\nSBMEH AS AFKO_SBMEH,\r\nSBMNG AS AFKO_SBMNG,\r\nSDATV AS AFKO_SDATV,\r\nSICHZ AS AFKO_SICHZ,\r\nSLSBS AS AFKO_SLSBS,\r\nSLSVN AS AFKO_SLSVN,\r\nSTLAL AS AFKO_STLAL,\r\nSTLAN AS AFKO_STLAN,\r\nSTLBEZ AS AFKO_STLBEZ,\r\nSTLNR AS AFKO_STLNR,\r\nSTLST AS AFKO_STLST,\r\nSTLTY AS AFKO_STLTY,\r\nSTUFE AS AFKO_STUFE,\r\nTERKZ AS AFKO_TERKZ,\r\nUPTER AS AFKO_UPTER,\r\nVORGZ AS AFKO_VORGZ,\r\nVWEGX AS AFKO_VWEGX,\r\nWEGXX AS AFKO_WEGXX,\r\nZAEHL AS AFKO_ZAEHL,\r\nZKRIZ AS AFKO_ZKRIZ\r\nFROM in0"
    )

    return df1
