from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from prophecy.libs import typed_lit
from PPLN_MD_MATL_5.config.ConfigStore import *
from PPLN_MD_MATL_5.udfs.UDFs import *

def sql_MD_MATL(spark: SparkSession) -> DataFrame:
    out0 = spark.sql(
        f"""
    WITH cte_f4104 AS
  (select ivlitm,MinShelfLifeInDays from (
select *,ROW_NUMBER() over (partition by ivlitm order by ivlitm DESC) as RNK from (
SELECT f4104_adt.ivlitm as ivlitm,
          CASE
              WHEN f4104_adt.ivdsc1 IS NOT NULL THEN f4104_adt.ivdsc1 * 30
              ELSE
                     (SELECT F6060002.gpurab * 30
                      FROM {Config.sourceDatabase}.F6060002 F6060002
      WHERE LOWER(TRIM(F6060002.gpgs1a)) = LOWER('R5841110')
      AND LOWER(TRIM(F6060002.gpgs2a)) = LOWER('MinShelfLife')
      AND F6060002._deleted_ = 'F')
          END AS MinShelfLifeInDays
   FROM {Config.sourceDatabase}.f4104_adt
   WHERE f4104_adt.ivxrt='XL'
     AND f4104_adt._deleted_ = 'F' ))where RNK = 1)
SELECT
    '{Config.sourceSystem}'   AS SRC_SYS_CD
,F4101_ADT.imlitm AS MATL_NUM
,TRIM(F4101_ADT.imglpt) AS MATL_TYPE_CD
,TRIM(F4101_ADT.imsrp5) AS BRND_CD
,TRIM(F4101_ADT.imsrp1) AS FRANCHISE_CD
,TRIM(F4101_ADT.imsrp2) AS LCL_PLNG_SUB_FRAN_CD
,NULL AS PRCHSNG_VAL_KEY_CD
,NULL AS DEL_IND
,TRIM(F4101_ADT.imprp7) AS MATL_GRP_CD
,NULL AS INDSTR_SECTR_CD
,TRIM(F4101_ADT.imuom1) AS BASE_UOM_CD
,CAST(F4101_ADT.imsld AS DECIMAL(18,4)) AS TOT_SHLF_LIF_DAYS_CNT
,CAST(cte_f4104.MinShelfLifeInDays AS DECIMAL(18, 4)) AS MIN_SHLF_RMN_LIF_DAYS_CNT
,TRIM(F4101_ADT.imstkt) AS MATL_STS_CD
,NULL AS DSTN_CHN_STS_CD
,NULL AS NET_WT_MEAS
,TRIM(F4101_ADT.imsrp3) AS PROD_HIER_CD
,NULL AS PRCMT_QUAL_MGMT_IND
,NULL AS STRG_CONDS_CD
,NULL AS LBL_TEMP_RNG
,NULL AS TRSPN_GRP_CD
,CASE WHEN TRIM(F4101_ADT.imsrce) IN ('0', '') OR TRIM(F4101_ADT.imsrce) IS NULL THEN '' ELSE 'X' END AS BTCH_MNG_IND
,TRIM(F4101_ADT.imdraw) AS MATL_DOC_NUM
,TRIM(F4101_ADT.imrvno) AS MATL_DOC_VERS_NUM
,TRIM(F4101_ADT.imdsc1) AS MATL_SHRT_DESC
,NULL AS MMS_SURGERY_TYPE_CD
,NULL AS MMS_MATL_TYPE_CD
,NULL AS PRMRY_PLNT_CD
,NULL AS MMS_FIN_CLSN_CD
,NULL AS MMS_STERILIZATION_IND
,TRIM(F4101_ADT.imaitm) AS MATL_CATLG_NUM
,NULL AS SRC_SECTR_CD
,TRIM(F4101_ADT.imlitm) AS MATL_PARNT_CD
,TRIM(F4101_ADT.imsrp4) AS MATL_SUB_TYPE_CD
,TRIM(F4101_ADT.imprp5) AS FIN_HIER_BASE_CD
,NULL AS IMPLNT_INSTM_IND
,NULL AS MATL_MOD_CD
,NULL AS KIT_IND
,NULL AS MMS_TEMP_SENS_IND
,NULL AS DIR_PART_MRKNG_CD
,TRIM(F4101_ADT.imsrp5) AS MATL_CAT_GRP_CD
,TRIM(F4101_ADT.imprp8) AS PLNG_HIER3_CD
,TRIM(F4101_ADT.imdraw) AS MATL_SPEC_NUM
,TRIM(F4101_ADT.imrvno) AS MATL_SPEC_VERS_NUM
,TRIM(F4101_ADT.imuser) AS CHG_BY
,NULL AS DOC_CHG_NUM
,NULL AS CNTNR_REQ
,NULL AS OLD_MATL_NUM
,NULL AS GRS_WT
,NULL AS ORDR_UNIT_PUR_UOM
,NULL AS CHEM_CMPLI
,NULL AS CRT_BY
,NULL AS CRT_ON_DTTM
,NULL AS LBL_TYPE
,NULL AS LBL_FORM
,NULL AS EXTRNL_MATL_GRP
,NULL AS MAX_LVL
,TRIM(F4101_ADT.imuwum) AS WT_UNIT
,NULL AS SIZE_DIM
,NULL AS PER_IN
,CASE
    WHEN LENGTH(F4101_ADT.imtday) = 6 THEN TO_TIMESTAMP(
      CONCAT(
        DATE_ADD(
          CAST(
            SUBSTRING(F4101_ADT.IMUPMJ + 1900000, 1, 4) AS DATE
          ),
          CAST(SUBSTRING(F4101_ADT.IMUPMJ, 4, 3) AS INT) -1
        ),
        \"\"\"\",
        F4101_ADT.imtday
      ),
      'yyyy-MM-ddHHmmss'
    )
    WHEN LENGTH(F4101_ADT.imtday) = 5 THEN TO_TIMESTAMP(
      CONCAT(
        DATE_ADD(
          CAST(
            SUBSTRING(F4101_ADT.IMUPMJ + 1900000, 1, 4) AS DATE
          ),
          CAST(SUBSTRING(F4101_ADT.IMUPMJ, 4, 3) AS INT) -1
        ),
        \"\"\"\",
        concat(0, F4101_ADT.imtday)
      ),
      'yyyy-MM-ddHHmmss'
    )
    ELSE TO_TIMESTAMP(
      DATE_ADD(
        CAST(SUBSTRING(F4101_ADT.IMUPMJ + 1900000, 1, 4) AS Date),
        CAST(SUBSTRING(F4101_ADT.IMUPMJ, 4, 3) as INT) -1
      )
    )
 END AS LAST_CHG_DT_TIME_DTTM
,NULL AS MATL_GRP_PKGNG_MATL
,NULL AS MATL_EXTRNL
,NULL AS STRG_PCT
,NULL AS VAL_FROM_XPLNT_DTTM
,NULL AS VAL_FROM_XDC_DTTM
,NULL AS INDSTR_STD_DESC
,NULL AS RD_RUL_SLED
,NULL AS SER_LVL
,NULL AS MATL_HAZ_CD
,NULL AS VAR_ORDR_UNT
,NULL AS PKGNG_MATL_TYPE
,TRIM(F4101_ADT.imvcud) AS VOL_UNIT
,CAST(TRIM(F4101_ADT.imuvm1) AS DECIMAL(18,4)) AS VOL
,NULL AS BSC_MATL
,NULL AS DOC_TYPE
,NULL AS DOC_PG_FMT
,NULL AS EAN_UPC
,NULL AS EAN_CAT
,NULL AS MFR_BOOK_PART_NUM
,NULL AS DIR_SHP_FL
,NULL AS FIN_PLNT
,NULL AS MAIN_STRG_LOC
,NULL AS PCS_PER_SLS_UNT
,TRIM(F4101_ADT.imprp4) AS PROD_LINE
,NULL AS MAKE_BUY_IN
,NULL AS STRT_PLNT
,NULL AS MATL_SHRT_DESC_UP_CASE
,TRIM(f0005_adt_s2.drdl01) AS MATL_TYPE_DESC
,TRIM(f0005_adt_s1.drdl01) AS FRAN_CD_DESC
,NULL AS BASE_UOM_DESC
,NULL AS OBJ_NUM
,NULL AS TYPE_OF_MATERIAL
,NULL AS STERILE
,TRIM(F4101_ADT.imsrp0) AS BRAVO_MINOR_CODE
,TRIM(f0005_adt.drdl01) AS BRAVO_MINOR_CODE_DESC
,NULL AS NDL_SLS_TYPE
,NULL AS SUTURE_LENGTH_INCH
,NULL AS SER_TYPE
,NULL AS GTIN_VRNT
,NULL AS MATL_GRP_DESC
,NULL AS MATL_GRP_DESC_2
,F4101_ADT.imitm AS SHRT_MATL_NUM
,TRIM(F4101_ADT.imprp1) AS CMMDTY
,NULL AS NDL_COLOR
,NULL AS NDL_ALLOY
,NULL AS SUTURE_USP
,NULL AS EAN_UPC_HRMZD
FROM {Config.sourceDatabase}.F4101_ADT F4101_ADT
LEFT JOIN cte_f4104 ON f4101_adt.imlitm = cte_f4104.ivlitm
LEFT JOIN {Config.sourceDatabase}.f0005_adt f0005_adt 
ON F4101_ADT.IMSRP0 = TRIM(f0005_adt.DRKY) 
AND TRIM(f0005_adt.DRSY) = '41'
AND f0005_adt.DRRT = '10'
AND f0005_adt._deleted_ = 'F'
LEFT JOIN {Config.sourceDatabase}.f0005_adt f0005_adt_s1 
ON F4101_ADT.IMSRP1 = TRIM(f0005_adt_s1.DRKY) 
AND TRIM(f0005_adt_s1.DRSY) = '41'
AND f0005_adt_s1.DRRT = 'S1'
AND f0005_adt_s1._deleted_ = 'F'
LEFT JOIN {Config.sourceDatabase}.f0005_adt f0005_adt_s2
ON F4101_ADT.IMSRP2 = TRIM(f0005_adt_s2.DRKY) 
AND TRIM(f0005_adt_s2.DRSY) = '41'
AND f0005_adt_s2.DRRT = 'S2'
AND f0005_adt_s2._deleted_ = 'F'
WHERE F4101_ADT._deleted_ = 'F'  
 
"""
    )

    return out0
