from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from prophecy.libs import typed_lit
from tbl_strct_MES_MD_GENEOLOGY.config.ConfigStore import *
from tbl_strct_MES_MD_GENEOLOGY.udfs.UDFs import *

def sql_MES_MD_SPEC(spark: SparkSession, ) -> (DataFrame):
    df1 = spark.sql(
        "select \ncast('' as STRING) as SRC_SYS_CD,\ncast('' as STRING) as SPEC_ID,\ncast('' as STRING) as OPR_ID,\ncast('' as STRING) as SPEC_BASE_ID,\ncast('' as BOOLEAN) as ALLW_OVRDS_IND,\ncast('' as STRING) as ALLW_RWRK_TO_TXT,\ncast('' as BOOLEAN) as ALWAYS_OVRD_EXPN_DT_IND,\ncast('' as BOOLEAN) as ASGN_UDI_IND,\ncast('' as BOOLEAN) as ASGN_UDI_1_IND,\ncast('' as STRING) as BP_SCALE_GRP_ID,\ncast('' as STRING) as CARR_AUTO_MODE_CD,\ncast('' as INT) as CHG_CNT,\ncast('' as STRING) as CHG_HIST_ID,\ncast('' as STRING) as DFLT_RUN_LVL_ID,\ncast('' as STRING) as DFLT_RUN_MC_BASE_ID,\ncast('' as STRING) as DFLT_RUN_RMC_ID,\ncast('' as STRING) as DOC_SET_ID,\ncast('' as STRING) as ELCTRNC_PCDR_ID,\ncast('' as STRING) as ELCTRNC_PCDR_BASE_ID,\ncast('' as STRING) as ENGR_CHG_ORDR_NUM,\ncast('' as STRING) as ESIG_TXN_MAP_GRP_ID,\ncast('' as STRING) as EXPN_PER_UOM_CD,\ncast('' as STRING) as EXPN_PER_VAL,\ncast('' as TIMESTAMP) as EXPN_TRX_DTTM,\ncast('' as STRING) as GSL_WRKF_ID,\ncast('' as STRING) as ICON_ID,\ncast('' as BOOLEAN) as IS_FRZN_IND,\ncast('' as BOOLEAN) as IS_LD_CARR_IND,\ncast('' as BOOLEAN) as IS_UNLD_CARR_IND,\ncast('' as BOOLEAN) as KEP_RSRS_ASGNMT_IND,\ncast('' as STRING) as LBL_PRT_MSG_1_TXT,\ncast('' as STRING) as LBL_PRT_MSG_2_TXT,\ncast('' as STRING) as LBL_TXN_MAP_GRP_ID,\ncast('' as TIMESTAMP) as MFG_TRX_DTTM,\ncast('' as STRING) as MAX_PRCS_TIME_VAL,\ncast('' as STRING) as MAX_QUE_TIME_ACTN_CD,\ncast('' as STRING) as MAX_QUE_TIME_VAL,\ncast('' as STRING) as MIN_PRCS_TIME_VAL,\ncast('' as STRING) as MIN_QUE_TIME_VAL,\ncast('' as STRING) as NOTES_TXT,\ncast('' as STRING) as OBJ_TYPE_ID,\ncast('' as STRING) as RECIPE_FILE_BASE_ID,\ncast('' as STRING) as RECIPE_FILE_ID,\ncast('' as STRING) as RSRS_GRP_ID,\ncast('' as STRING) as RSRS_LINE_GRP_AVLBLTY_TXT,\ncast('' as BOOLEAN) as RSRS_LINE_GRP_MNT_CHK_IND,\ncast('' as STRING) as SCHDLNG_DTL_ID,\ncast('' as STRING) as SETUP_BASE_ID,\ncast('' as STRING) as SETUP_ID,\ncast('' as STRING) as SPEC_DESC,\ncast('' as STRING) as SPEC_RVSN_ID,\ncast('' as STRING) as STS_CD,\ncast('' as STRING) as TRNG_REQ_GRP_ID,\ncast('' as STRING) as USER_DEFIN_STRNG_TXT,\ncast('' as BOOLEAN) as VLD_LOT_SMPLG_CMPLT_IND,\ncast('' as BOOLEAN) as VLD_MATL_CNSMPTN_IND,\ncast('' as BOOLEAN) as VLD_PDDC_IND,\ncast('' as BOOLEAN) as VLD_PLC_VERS_IND,\ncast('' as BOOLEAN) as VLD_UDI_IND,\ncast('' as STRING) as VLD_PCDR_BASE_ID,\ncast('' as STRING) as VLD_PCDR_ID,\ncast('' as STRING) as WARN_QUE_TIME_VAL,\ncast('' as STRING) as WIP_MSG_DEF_MGR_ID,\ncast('' as INT) as DAI_ETL_ID,\ncast('' as TIMESTAMP) as DAI_CRT_DTTM,\ncast('' as TIMESTAMP) as DAI_UPDT_DTTM,\ncast('' as timestamp) as _l0_upt_,\n cast('' as timestamp) as _l1_upt_,\n cast('' as string) as _pk_md5_,\n cast('' as string) as _pk_ \n limit 0"
    )

    return df1
