from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from prophecy.libs import typed_lit
from tbl_strct_MES_MD_SITE_PLANT.config.ConfigStore import *
from tbl_strct_MES_MD_SITE_PLANT.udfs.UDFs import *

def sql_MES_MD_LOC(spark: SparkSession, ) -> (DataFrame):
    df1 = spark.sql(
        "select \ncast('' as STRING) as SRC_SYS_CD,\ncast('' as STRING) as LOC_ID,\ncast('' as STRING) as FCTRY_ID,\ncast('' as STRING) as CASE_ID_PAD_CHAR_TXT,\ncast('' as STRING) as CASE_ID_PAD_LGTH_VAL,\ncast('' as INT) as CASE_SEQ_NBR,\ncast('' as INT) as CHG_CNT,\ncast('' as STRING) as CHG_STS_ID,\ncast('' as STRING) as CL_END_TEMP_VAL,\ncast('' as STRING) as DFLT_LINE_UOM_ID,\ncast('' as STRING) as EXPT_IMPT_KEY_VAL,\ncast('' as STRING) as EXPSR_DUR_MINS_VAL,\ncast('' as STRING) as EXPSR_DUR_VAL,\ncast('' as STRING) as EXPSR_TLRNC_VAL,\ncast('' as STRING) as HIGH_EXPSR_TEMP_VAL,\ncast('' as STRING) as HIGH_PRESR_VAL,\ncast('' as STRING) as ICON_ID,\ncast('' as BOOLEAN) as IS_FRZN_IND,\ncast('' as BOOLEAN) as IS_INSITE_RTRN_IND,\ncast('' as BOOLEAN) as IS_LGCY_APP_ABSR_IND,\ncast('' as BOOLEAN) as IS_LINE_UDI_IND,\ncast('' as BOOLEAN) as IS_M8_LINE_IND,\ncast('' as BOOLEAN) as IS_PLC_LOT_TCKG_ENABL_IND,\ncast('' as BOOLEAN) as IS_PLC_VERS_CLCT_ENABL_IND,\ncast('' as BOOLEAN) as IS_PROD_CONV_ENABL_IND,\ncast('' as STRING) as LBL_PRTR_NM_ID,\ncast('' as STRING) as LABWARE_VERS_VAL,\ncast('' as STRING) as LINE_CD,\ncast('' as STRING) as LINE_CHAR_CASE_PLLT_LBL_CD,\ncast('' as STRING) as LINE_NUM,\ncast('' as STRING) as LOC_CD,\ncast('' as STRING) as LOC_DESC,\ncast('' as BOOLEAN) as LOC_FTN_IND,\ncast('' as STRING) as LOC_NM,\ncast('' as STRING) as LOW_EXPSR_TEMP_VAL,\ncast('' as STRING) as LOW_PRESR_VAL,\ncast('' as STRING) as MAX_LENES_ON_RACK_VAL,\ncast('' as STRING) as MAX_PH_INTV_DUR_VAL,\ncast('' as STRING) as MAX_RTD_VAL,\ncast('' as STRING) as MAX_SPLT_SPC_GRP_VAL,\ncast('' as INT) as MAX_STERILIZATION_CNT,\ncast('' as STRING) as MAX_STERILIZATION_STRT_DUR_VAL,\ncast('' as STRING) as MIN_PH_INTV_DUR_VAL,\ncast('' as STRING) as MIN_RTD_VAL,\ncast('' as STRING) as MIN_STERILIZATION_STRT_DUR_VAL,\ncast('' as STRING) as MOLD_CAVITY_CONFIG_VAL,\ncast('' as INT) as OBJ_TYPE_ID,\ncast('' as STRING) as PLLT_ID_PAD_CHAR_VAL,\ncast('' as STRING) as PLLT_ID_PAD_LGTH_VAL,\ncast('' as INT) as PLLT_SEQ_NBR,\ncast('' as STRING) as PH_ORDR_NUM,\ncast('' as STRING) as PLC_EXPSR_TIME_MAX_MIN_VAL,\ncast('' as STRING) as PLC_LINE_CD,\ncast('' as STRING) as PROD_CONV_LINE_ID,\ncast('' as INT) as RDT_CNT,\ncast('' as INT) as REQ_RTDS_CNT,\ncast('' as STRING) as SAP_LINE_CD,\ncast('' as STRING) as SAP_LINE_NUM,\ncast('' as INT) as STS_ID,\ncast('' as STRING) as STERILIZATION_TEST_DEC_VAL,\ncast('' as STRING) as TEST_DUR_DEC_VAL,\ncast('' as INT) as TOT_CASE_PER_PLLT_NBR,\ncast('' as BOOLEAN) as USE_RACKS_IND,\ncast('' as STRING) as WIP_MSG_DEF_MGR_ID,\ncast('' as INT) as DAI_ETL_ID,\ncast('' as TIMESTAMP) as DAI_CRT_DTTM,\ncast('' as TIMESTAMP) as DAI_UPDT_DTTM,\ncast('' as timestamp) as _l0_upt_,\n cast('' as timestamp) as _l1_upt_,\n cast('' as string) as _pk_md5_,\n cast('' as string) as _pk_ \n limit 0"
    )

    return df1
