from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from prophecy.libs import typed_lit
from PPLN_MD_MATL_8.config.ConfigStore import *
from PPLN_MD_MATL_8.udfs.UDFs import *

def sql_MD_MATL(spark: SparkSession) -> DataFrame:
    out0 = spark.sql(
        f"""
    SELECT DISTINCT
    '{Config.sourceSystem}'   AS SRC_SYS_CD
,F4101.imlitm AS MATL_NUM
,TRIM(F4101.imsrp2) AS MATL_TYPE_CD
,NULL AS BRND_CD
,TRIM(F4101.imsrp1) AS FRANCHISE_CD
,TRIM(F4101.imprp7) AS LCL_PLNG_SUB_FRAN_CD
,NULL AS PRCHSNG_VAL_KEY_CD
,NULL AS DEL_IND
,TRIM(F4101.imprp4) AS MATL_GRP_CD
,NULL AS INDSTR_SECTR_CD
,TRIM(F4101.imuom1) AS BASE_UOM_CD
,CAST(F4101.imsld AS DECIMAL(18,4)) AS TOT_SHLF_LIF_DAYS_CNT
,NULL AS MIN_SHLF_RMN_LIF_DAYS_CNT
,TRIM(F4101.imstkt) AS MATL_STS_CD
,TRIM(F4101.imprp3) AS DSTN_CHN_STS_CD
,NULL AS NET_WT_MEAS
,TRIM(F4101.imsrp9) AS PROD_HIER_CD
,NULL AS PRCMT_QUAL_MGMT_IND
,NULL AS STRG_CONDS_CD
,NULL AS LBL_TEMP_RNG
,NULL AS TRSPN_GRP_CD
,CASE WHEN TRIM(F4101.imsrce) IN ('0', '') OR TRIM(F4101.imsrce) IS NULL THEN '' ELSE 'X' END AS BTCH_MNG_IND
,TRIM(F4101.imdraw) AS MATL_DOC_NUM
,TRIM(F4101.imrvno) AS MATL_DOC_VERS_NUM
,CONCAT(TRIM(F4101.imdsc1),'; ',TRIM(F4101.imdsc2)) AS MATL_SHRT_DESC
,NULL AS MMS_SURGERY_TYPE_CD
,NULL AS MMS_MATL_TYPE_CD
,NULL AS PRMRY_PLNT_CD
,NULL AS MMS_FIN_CLSN_CD
,NULL AS MMS_STERILIZATION_IND
,TRIM(F4101.imaitm) AS MATL_CATLG_NUM
,NULL AS SRC_SECTR_CD
,NULL AS MATL_PARNT_CD
,NULL AS MATL_SUB_TYPE_CD
,TRIM(F4101.imglpt) AS FIN_HIER_BASE_CD
,NULL AS IMPLNT_INSTM_IND
,NULL AS MATL_MOD_CD
,NULL AS KIT_IND
,NULL AS MMS_TEMP_SENS_IND
,NULL AS DIR_PART_MRKNG_CD
,TRIM(F4101.imprp2) AS MATL_CAT_GRP_CD
,TRIM(F4101.imsrp6) AS PLNG_HIER3_CD
,NULL AS MATL_SPEC_NUM
,NULL AS MATL_SPEC_VERS_NUM
,TRIM(F4101.imuser) AS CHG_BY
,NULL AS DOC_CHG_NUM
,NULL AS CNTNR_REQ
,NULL AS OLD_MATL_NUM
,NULL AS GRS_WT
,NULL AS ORDR_UNIT_PUR_UOM
,NULL AS CHEM_CMPLI
,NULL AS CRT_BY
,NULL AS CRT_ON_DTTM
,NULL AS LBL_TYPE
,NULL AS LBL_FORM
,NULL AS EXTRNL_MATL_GRP
,NULL AS MAX_LVL
,trim(F4101.imuwum) AS WT_UNIT
,NULL AS SIZE_DIM
,NULL AS PER_IN
, CASE
    WHEN LENGTH(f4101.imtday) = 6 THEN TO_TIMESTAMP(
      CONCAT(
        DATE_ADD(
          CAST(
            SUBSTRING(f4101.IMUPMJ + 1900000, 1, 4) AS DATE
          ),
          CAST(SUBSTRING(f4101.IMUPMJ, 4, 3) AS INT) -1
        ),
        \"\"\"\",
        f4101.imtday
      ),
      'yyyy-MM-ddHHmmss'
    )
    WHEN LENGTH(f4101.imtday) = 5 THEN TO_TIMESTAMP(
      CONCAT(
        DATE_ADD(
          CAST(
            SUBSTRING(f4101.IMUPMJ + 1900000, 1, 4) AS DATE
          ),
          CAST(SUBSTRING(f4101.IMUPMJ, 4, 3) AS INT) -1
        ),
        \"\"\"\",
        concat(0, f4101.imtday)
      ),
      'yyyy-MM-ddHHmmss'
    )
    ELSE TO_TIMESTAMP(
      DATE_ADD(
        CAST(SUBSTRING(f4101.IMUPMJ + 1900000, 1, 4) AS Date),
        CAST(SUBSTRING(f4101.IMUPMJ, 4, 3) as INT) -1
      )
    )
  END AS LAST_CHG_DT_TIME_DTTM
,NULL AS MATL_GRP_PKGNG_MATL
,NULL AS MATL_EXTRNL
,NULL AS STRG_PCT
,NULL AS VAL_FROM_XPLNT_DTTM
,NULL AS VAL_FROM_XDC_DTTM
,NULL AS INDSTR_STD_DESC
,NULL AS RD_RUL_SLED
,NULL AS SER_LVL
,NULL AS MATL_HAZ_CD
,NULL AS VAR_ORDR_UNT
,NULL AS PKGNG_MATL_TYPE
,TRIM(F4101.imuvm1) AS VOL_UNIT
,CAST(TRIM(F4101.imvcud) AS DECIMAL(18,4))  AS VOL
,NULL AS BSC_MATL
,TRIM(F4101.imlnty) AS DOC_TYPE
,NULL AS DOC_PG_FMT
,NULL AS EAN_UPC
,NULL AS EAN_CAT
,NULL AS MFR_BOOK_PART_NUM
,NULL AS DIR_SHP_FL
,NULL AS FIN_PLNT
,NULL AS MAIN_STRG_LOC
,NULL AS PCS_PER_SLS_UNT
,NULL AS PROD_LINE
,NULL AS MAKE_BUY_IN
,NULL AS STRT_PLNT
,NULL AS MATL_SHRT_DESC_UP_CASE
,TRIM(f0005_s2.drdl01) AS MATL_TYPE_DESC
,TRIM(f0005_s1.drdl01) AS FRAN_CD_DESC
,NULL AS BASE_UOM_DESC
,NULL AS OBJ_NUM
,NULL AS TYPE_OF_MATERIAL
,trim(F4101.imprp1) AS STERILE
,TRIM(F4101.imsrp0) AS BRAVO_MINOR_CODE
,TRIM(f0005.drdl01) AS BRAVO_MINOR_CODE_DESC
,NULL AS NDL_SLS_TYPE
,NULL AS SUTURE_LENGTH_INCH
,NULL AS SER_TYPE
,NULL AS GTIN_VRNT
,TRIM(f0005_p4.drdl01) AS MATL_GRP_DESC
,NULL AS MATL_GRP_DESC_2
,f4101.imitm AS SHRT_MATL_NUM
,NULL AS CMMDTY
,NULL AS NDL_COLOR
,NULL AS NDL_ALLOY
,NULL AS SUTURE_USP
,NULL AS EAN_UPC_HRMZD
FROM {Config.sourceDatabase}.F4101 F4101
LEFT JOIN {Config.sourceDatabase}.f0005 f0005 
ON F4101.IMSRP0 = TRIM(f0005.DRKY) 
AND TRIM(f0005.DRSY) = '41'
AND f0005.DRRT = '10'
AND f0005._deleted_ = 'F'
LEFT JOIN {Config.sourceDatabase}.f0005 f0005_s1 
ON F4101.IMSRP1 = TRIM(f0005_s1.DRKY) 
AND TRIM(f0005_s1.DRSY) = '41'
AND f0005_s1.DRRT = 'S1'
AND f0005_s1._deleted_ = 'F'
LEFT JOIN {Config.sourceDatabase}.f0005 f0005_s2
ON F4101.IMSRP2 = TRIM(f0005_s2.DRKY) 
AND TRIM(f0005_s2.DRSY) = '41'
AND f0005_s2.DRRT = 'S2'
AND f0005_s2._deleted_ = 'F'
LEFT JOIN {Config.sourceDatabase}.f0005 f0005_p4
ON F4101.IMPRP4 = TRIM(f0005_p4.DRKY)
AND TRIM(f0005_p4.DRSY) = '41'
AND f0005_p4.DRRT = 'P4'
AND f0005_p4._deleted_ = 'F'
WHERE F4101._deleted_ = 'F'  
 
"""
    )

    return out0
