name: CDL_MD_L1
description: Project for storing MD L1 pipelines - tied to JEKT
version: 0.0.1
author: hgermi1@its.jnj.com
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: cdl_md_l1
  parentArtefactID: cdl_l1_team
  buildSystem: wheel
  author: null
  createdAt: '2023-03-24 15:54:27'
  modifiedAt: '2023-03-24 15:54:27'
pipelines:
  pipelines/SAP_01_MD_CUST:
    name: SAP_01_MD_CUST
    description: ''
    author: hgermi1@its.jnj.com
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-04-15 17:35:18'
    modifiedAt: '2023-04-20 15:30:51'
    datasets:
      inputs:
      - datasets/DS_SAP_01_KNA1
      - datasets/DS_SAP_01_T016T
      - datasets/DS_SAP_01_TVAST
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/SAP_01_MD_SHIP_SVS:
    name: SAP_01_MD_CUST_SVS
    description: ''
    author: hgermi1@its.jnj.com
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-04-18 01:51:03'
    modifiedAt: '2023-04-20 00:51:44'
    datasets:
      inputs:
      - datasets/DS_SAP_01_T016T
      - datasets/DS_SAP_01_TVAST
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/SAP_01_MD_CUST_HCS:
    name: SAP_01_MD_CUST_HCS
    description: ''
    author: hgermi1@its.jnj.com
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-04-19 22:04:42'
    modifiedAt: '2023-04-20 02:00:52'
    datasets:
      inputs:
      - datasets/DS_SAP_01_T016T
      - datasets/DS_SAP_01_TVAST
      - datasets/DS_SAP_02_KNA1
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/DS_SAP_01_KNA1:
    name: DS_SAP_01_KNA1
    description: ''
    author: hgermi1@its.jnj.com
    createdAt: '2023-04-15 17:41:10'
    modifiedAt: '2023-04-20 15:30:29'
    mode: batch
    physicalDatasets:
      CDL_L1_Dev:
        fabricId: 32
        datasetType: Database
        description: ''
        author: hgermi1@its.jnj.com
        createdAt: '2023-04-15 17:41:10'
        modifiedAt: '2023-04-15 17:41:10'
  datasets/DS_SAP_01_TVAST:
    name: DS_SAP_01_TVAST
    description: ''
    author: hgermi1@its.jnj.com
    createdAt: '2023-04-15 18:54:15'
    modifiedAt: '2023-04-15 18:54:15'
    mode: batch
    physicalDatasets:
      CDL_L1_Dev:
        fabricId: 32
        datasetType: Database
        description: ''
        author: hgermi1@its.jnj.com
        createdAt: '2023-04-15 18:54:15'
        modifiedAt: '2023-04-15 18:54:15'
  datasets/DS_SAP_01_T016T:
    name: DS_SAP_01_T016T
    description: ''
    author: hgermi1@its.jnj.com
    createdAt: '2023-04-15 18:55:51'
    modifiedAt: '2023-04-15 18:55:51'
    mode: batch
    physicalDatasets:
      CDL_L1_Dev:
        fabricId: 32
        datasetType: Database
        description: ''
        author: hgermi1@its.jnj.com
        createdAt: '2023-04-15 18:55:51'
        modifiedAt: '2023-04-15 18:55:51'
  datasets/DS_SAP_02_KNA1:
    name: DS_SAP_02_KNA1
    description: ''
    author: hgermi1@its.jnj.com
    createdAt: '2023-04-19 22:10:57'
    modifiedAt: '2023-04-19 22:11:20'
    mode: batch
    physicalDatasets:
      CDL_L1_Dev:
        fabricId: 32
        datasetType: Database
        description: ''
        author: hgermi1@its.jnj.com
        createdAt: '2023-04-19 22:10:57'
        modifiedAt: '2023-04-19 22:10:57'
templates: {}
jobs: {}
functions:
  author: null
  createdAt: '2023-04-15 17:35:18'
  modifiedAt: '2023-04-15 17:35:18'
  gems: {}
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels: {}
sqlPipeline: null
dependencies: []
projectDependencies: {}
pipelineConfigurations: {}
