name: CDL_MD_L1
description: ''
version: 0.0.1
author: lsorarra@its.jnj.com
language: python
buildSystem: wheel
pipelines:
  pipelines/JDE_01_DEU_F0401:
    name: JDE_01_DEU_F0401
    description: ''
    author: lsorarra@its.jnj.com
    mode: batch
    language: python
    createdAt: '2023-03-21 17:01:44'
    modifiedAt: '2023-03-21 17:43:35'
    datasets:
      inputs:
      - datasets/DS_JDE_01_F0101
      - datasets/DS_JDE_01_F0401
      outputs: []
    dependencies: {}
datasets:
  datasets/DS_JDE_01_F0401:
    name: DS_JDE_01_F0401
    description: ''
    author: lsorarra@its.jnj.com
    createdAt: '2023-03-21 17:17:48'
    modifiedAt: '2023-03-21 17:17:48'
    mode: batch
    physicalDatasets:
      CDL_L1_Dev:
        fabricId: 32
        datasetType: Database
        description: ''
        author: lsorarra@its.jnj.com
        createdAt: '2023-03-21 17:17:48'
        modifiedAt: '2023-03-21 17:17:48'
  datasets/DS_JDE_01_F0101:
    name: DS_JDE_01_F0101
    description: ''
    author: lsorarra@its.jnj.com
    createdAt: '2023-03-21 17:43:17'
    modifiedAt: '2023-03-21 17:43:17'
    mode: batch
    physicalDatasets:
      CDL_L1_Dev:
        fabricId: 32
        datasetType: Database
        description: ''
        author: lsorarra@its.jnj.com
        createdAt: '2023-03-21 17:43:17'
        modifiedAt: '2023-03-21 17:43:17'
templates: {}
jobs: {}
libraries: []
subgraphs: {}
sqlModels: {}
sqlPipeline: null
dependencies: []
projectDependencies: {}
pipelineConfigurations: {}
