name: CDL_MD_L1
description: ''
version: 0.0.1
author: natkins7@its.jnj.com
language: python
buildSystem: wheel
pipelines:
  pipelines/JDE_01_MD_MATL_INV:
    name: JDE_01_MD_MATL_INV
    description: 'JDE Systems for MD_MATL_INV '
    author: natkins7@its.jnj.com
    mode: batch
    language: python
    createdAt: '2023-03-20 08:44:36'
    modifiedAt: '2023-03-22 12:34:16'
    datasets:
      inputs:
      - datasets/DS_JDE_01_F4101
      - datasets/DS_JDE_01_F41021
      outputs:
      - datasets/MD_MATL_INV_SWAP
    dependencies: {}
datasets:
  datasets/DS_JDE_01_F4101:
    name: DS_JDE_01_F4101
    description: ''
    author: natkins7@its.jnj.com
    createdAt: '2023-03-20 13:56:03'
    modifiedAt: '2023-03-21 10:11:11'
    mode: batch
    physicalDatasets:
      CDL_L1_Dev:
        fabricId: 32
        datasetType: Database
        description: ''
        author: natkins7@its.jnj.com
        createdAt: '2023-03-20 13:56:03'
        modifiedAt: '2023-03-20 13:56:03'
  datasets/DS_JDE_01_F41021:
    name: DS_JDE_01_F41021
    description: ''
    author: natkins7@its.jnj.com
    createdAt: '2023-03-20 14:47:11'
    modifiedAt: '2023-03-21 09:58:24'
    mode: batch
    physicalDatasets:
      CDL_L1_Dev:
        fabricId: 32
        datasetType: Database
        description: ''
        author: natkins7@its.jnj.com
        createdAt: '2023-03-20 14:47:11'
        modifiedAt: '2023-03-20 14:47:11'
  datasets/MD_MATL_INV_SWAP:
    name: MD_MATL_INV_SWAP
    description: ''
    author: natkins7@its.jnj.com
    createdAt: '2023-03-21 11:51:31'
    modifiedAt: '2023-03-22 12:34:16'
    mode: batch
    physicalDatasets:
      CDL_L1_Dev:
        fabricId: 32
        datasetType: Database
        description: ''
        author: natkins7@its.jnj.com
        createdAt: '2023-03-21 11:51:31'
        modifiedAt: '2023-03-21 11:51:31'
templates: {}
jobs: {}
libraries: []
subgraphs: {}
sqlModels: {}
sqlPipeline: null
dependencies: []
projectDependencies: {}
pipelineConfigurations: {}
