name: CDL_MD_L1
description: Project for storing MD L1 pipelines - tied to JEKT
version: 0.0.1
author: jcovezd1@its.jnj.com
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: cdl_md_l1
  parentArtefactID: cdl_l1_team
  buildSystem: wheel
  author: null
  createdAt: '2023-03-24 12:57:11'
  modifiedAt: '2023-03-24 12:57:11'
pipelines:
  pipelines/SAP_MD_DELV_LINE_BBA_BBL_BBN:
    name: SAP_MD_DELV_LINE_BBA_BBL_BBN
    description: ''
    author: jcovezd1@its.jnj.com
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-04-03 18:08:25'
    modifiedAt: '2023-04-04 16:58:37'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/DS_SAP_01_LIPS:
    name: DS_SAP_01_LIPS
    description: ''
    author: jcovezd1@its.jnj.com
    createdAt: '2023-04-03 18:36:36'
    modifiedAt: '2023-04-03 18:36:36'
    mode: batch
    physicalDatasets:
      CDL_L1_Dev:
        fabricId: 32
        datasetType: Database
        description: ''
        author: jcovezd1@its.jnj.com
        createdAt: '2023-04-03 18:36:36'
        modifiedAt: '2023-04-03 18:36:36'
  datasets/DS_SAP_01_LIKP:
    name: DS_SAP_01_LIKP
    description: ''
    author: jcovezd1@its.jnj.com
    createdAt: '2023-04-03 18:37:55'
    modifiedAt: '2023-04-03 18:37:56'
    mode: batch
    physicalDatasets:
      CDL_L1_Dev:
        fabricId: 32
        datasetType: Database
        description: ''
        author: jcovezd1@its.jnj.com
        createdAt: '2023-04-03 18:37:55'
        modifiedAt: '2023-04-03 18:37:55'
  datasets/DS_SAP_01_VBAK:
    name: DS_SAP_01_VBAK
    description: ''
    author: jcovezd1@its.jnj.com
    createdAt: '2023-04-03 18:39:06'
    modifiedAt: '2023-04-03 18:39:06'
    mode: batch
    physicalDatasets:
      CDL_L1_Dev:
        fabricId: 32
        datasetType: Database
        description: ''
        author: jcovezd1@its.jnj.com
        createdAt: '2023-04-03 18:39:06'
        modifiedAt: '2023-04-03 18:39:06'
  datasets/DS_SAP_01_VBAP:
    name: DS_SAP_01_VBAP
    description: ''
    author: jcovezd1@its.jnj.com
    createdAt: '2023-04-03 18:40:04'
    modifiedAt: '2023-04-03 18:40:04'
    mode: batch
    physicalDatasets:
      CDL_L1_Dev:
        fabricId: 32
        datasetType: Database
        description: ''
        author: jcovezd1@its.jnj.com
        createdAt: '2023-04-03 18:40:04'
        modifiedAt: '2023-04-03 18:40:04'
templates: {}
jobs: {}
functions:
  author: null
  createdAt: '2023-03-31 15:58:58'
  modifiedAt: '2023-03-31 15:58:58'
  gems: {}
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels: {}
sqlPipeline: null
dependencies: []
projectDependencies: {}
pipelineConfigurations: {}
