name: CDL_MD_L1
description: ''
version: 0.0.1
author: ypatel8@its.jnj.com
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: cdl_md_l1
  parentArtefactID: cdl_l1_team
  buildSystem: wheel
  author: null
  createdAt: '2023-03-24 13:00:44'
  modifiedAt: '2023-03-24 13:00:44'
pipelines:
  pipelines/SAP_01_MD_MATL_INV:
    name: SAP_01_MD_MATL_INV
    description: ''
    author: ypatel8@its.jnj.com
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-03-22 13:21:05'
    modifiedAt: '2023-03-30 17:14:56'
    datasets:
      inputs:
      - datasets/DS_SAP_01_MARA
      - datasets/DS_SAP_01_NSDM_V_MARD
      - datasets/DS_SAP_01_NSDM_V_MCHB
      - datasets/DS_SAP_01_NSDM_V_MSKU
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/DS_SAP_01_NSDM_V_MARD:
    name: DS_SAP_01_NSDM_V_MARD
    description: ''
    author: ypatel8@its.jnj.com
    createdAt: '2023-03-30 13:30:19'
    modifiedAt: '2023-03-30 13:30:19'
    mode: batch
    physicalDatasets:
      CDL_L1_Dev:
        fabricId: 32
        datasetType: Database
        description: ''
        author: ypatel8@its.jnj.com
        createdAt: '2023-03-30 13:30:19'
        modifiedAt: '2023-03-30 13:30:19'
  datasets/DS_SAP_01_NSDM_V_MCHB:
    name: DS_SAP_01_NSDM_V_MCHB
    description: ''
    author: ypatel8@its.jnj.com
    createdAt: '2023-03-30 13:44:55'
    modifiedAt: '2023-03-30 13:44:55'
    mode: batch
    physicalDatasets:
      CDL_L1_Dev:
        fabricId: 32
        datasetType: Database
        description: ''
        author: ypatel8@its.jnj.com
        createdAt: '2023-03-30 13:44:55'
        modifiedAt: '2023-03-30 13:44:55'
  datasets/DS_SAP_01_NSDM_V_MSKU:
    name: DS_SAP_01_NSDM_V_MSKU
    description: ''
    author: ypatel8@its.jnj.com
    createdAt: '2023-03-30 13:50:42'
    modifiedAt: '2023-03-30 13:50:42'
    mode: batch
    physicalDatasets:
      CDL_L1_Dev:
        fabricId: 32
        datasetType: Database
        description: ''
        author: ypatel8@its.jnj.com
        createdAt: '2023-03-30 13:50:42'
        modifiedAt: '2023-03-30 13:50:42'
  datasets/DS_SAP_01_MARA:
    name: DS_SAP_01_MARA
    description: ''
    author: ypatel8@its.jnj.com
    createdAt: '2023-03-30 17:04:28'
    modifiedAt: '2023-03-30 17:04:28'
    mode: batch
    physicalDatasets:
      CDL_L1_Dev:
        fabricId: 32
        datasetType: Database
        description: ''
        author: ypatel8@its.jnj.com
        createdAt: '2023-03-30 17:04:28'
        modifiedAt: '2023-03-30 17:04:28'
templates: {}
jobs: {}
functions:
  author: null
  createdAt: '2023-03-24 13:00:44'
  modifiedAt: '2023-03-24 13:00:44'
  gems: {}
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels: {}
sqlPipeline: null
dependencies: []
projectDependencies: {}
pipelineConfigurations: {}
