name: CDL_MD_L1
description: ''
version: 0.0.1
author: smille29@its.jnj.com
language: python
buildSystem: wheel
pipelines:
  pipelines/SAP_01_MD_SER_NUM_STOCK_SGMNT:
    name: SAP_01_MD_SER_NUM_STOCK_SGMNT
    description: EDM MD_SER_NUM_STOCK_SGMNT for some SAP System that have the DISUB_OWNER
      field
    author: smille29@its.jnj.com
    mode: batch
    language: python
    createdAt: '2023-03-13 20:16:19'
    datasets:
      inputs:
      - datasets/DS_SAP_EQBS_01
      outputs: []
    dependencies: {}
datasets:
  datasets/DS_SAP_EQBS_01:
    name: DS_SAP_EQBS_01
    description: ''
    author: smille29@its.jnj.com
    createdAt: '2023-03-13 20:29:35'
    mode: batch
    physicalDatasets:
      CDL_L1_Dev:
        fabricId: 32
        datasetType: Database
        description: ''
        author: smille29@its.jnj.com
        createdAt: '2023-03-13 20:29:35'
templates: {}
jobs: {}
libraries: []
subgraphs: {}
sqlModels: {}
sqlPipeline: null
dependencies: []
projectDependencies: {}
pipelineConfigurations: {}
