name: CDL_MD_L1
description: ''
version: 0.0.1
author: jcovezd1@its.jnj.com
language: python
buildSystem: wheel
pipelines:
  pipelines/SAP_01_MD_BILL_DOC_HDR:
    name: SAP_01_MD_BILL_DOC_HDR
    description: ''
    author: jcovezd1@its.jnj.com
    mode: batch
    language: python
    createdAt: '2023-03-17 19:02:14'
    modifiedAt: '2023-03-17 19:03:46'
    datasets:
      inputs: []
      outputs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
libraries: []
subgraphs: {}
sqlModels: {}
sqlPipeline: null
dependencies: []
projectDependencies: {}
pipelineConfigurations: {}
