from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from prophecy.libs import typed_lit
from sap_md_bill_doc_hdr_bba_bbn.config.ConfigStore import *
from sap_md_bill_doc_hdr_bba_bbn.udfs.UDFs import *

def SELECT_VBRK(spark: SparkSession, in0: DataFrame) -> DataFrame:
    return in0.select(
        col("SPART"), 
        col("FKART"), 
        col("VKORG"), 
        col("VTWEG"), 
        col("VBELN"), 
        col("FKTYP"), 
        col("VBTYP"), 
        col("KUNRG"), 
        col("KUNAG"), 
        col("KUNWE"), 
        col("ERDAT"), 
        col("ERZET"), 
        col("FKDAT"), 
        col("FKDAT_RL"), 
        col("WAERK"), 
        col("ERNAM"), 
        col("KALSM"), 
        col("KNUMV"), 
        col("VSBED"), 
        col("GJAHR"), 
        col("POPER"), 
        col("KDGRP"), 
        col("INCO1"), 
        col("INCO2"), 
        col("RFBSK"), 
        col("KURRF"), 
        col("VALTG"), 
        col("VALDT"), 
        col("ZTERM"), 
        col("KTGRD"), 
        col("LAND1"), 
        col("REGIO"), 
        col("BUKRS"), 
        col("TAXK1"), 
        col("NETWR"), 
        col("ZUKRI"), 
        col("STWAE"), 
        col("AEDAT"), 
        col("FKART_RL"), 
        col("KKBER"), 
        col("KNKLI"), 
        col("CMWAE"), 
        col("CMKUF"), 
        col("HITYP_PR"), 
        col("BSTNK_VF"), 
        col("VBUND"), 
        col("LANDTX"), 
        col("STCEG_H"), 
        col("STCEG_L"), 
        col("XBLNR"), 
        col("ZUONR"), 
        col("MWSBK"), 
        col("LOGSYS"), 
        col("KURRF_DAT"), 
        col("KIDNO"), 
        col("NUMPG"), 
        col("BUCHK"), 
        col("RELIK"), 
        col("KONDA"), 
        col("BZIRK"), 
        col("PLTYP"), 
        col("TAXK2"), 
        col("TAXK3"), 
        col("TAXK4"), 
        col("TAXK5"), 
        col("TAXK6"), 
        col("TAXK7"), 
        col("TAXK8"), 
        col("TAXK9"), 
        col("FKSTO"), 
        col("_upt_")
    )
