from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from prophecy.libs import typed_lit
from tbl_strct_MES_MD_WORKFLOW.config.ConfigStore import *
from tbl_strct_MES_MD_WORKFLOW.udfs.UDFs import *

def sql_MES_MD_WRKF(spark: SparkSession, ) -> (DataFrame):
    df1 = spark.sql(
        "select \ncast('' as STRING) as SRC_SYS_CD,\ncast('' as STRING) as WRKF_ID,\ncast('' as STRING) as WRKF_BASE_ID,\ncast('' as STRING) as CTN_LBL_CLCT_STEP_ID,\ncast('' as STRING) as CTN_OPR_ID,\ncast('' as STRING) as CASE_LBL_RECON_STEP_ID,\ncast('' as INT) as CHG_CNT,\ncast('' as STRING) as CHG_HIST_ID,\ncast('' as STRING) as CKLST_HEAT_SEAL_ID,\ncast('' as STRING) as CKLST_HYDRATION_ID,\ncast('' as STRING) as CKLST_INJECTION_MOLDING_ID,\ncast('' as STRING) as CKLST_LEN_FABRICATION_ID,\ncast('' as STRING) as CKLST_POST_HYDRATION_ID,\ncast('' as STRING) as CKLST_QA_ID,\ncast('' as STRING) as CKLST_SEC_PACK_ID,\ncast('' as STRING) as CKLST_STERILIZATION_ID,\ncast('' as STRING) as DATA_CLCT_DEF_CTN_LBL_ID,\ncast('' as STRING) as DATA_CLCT_DEF_FOIL_LAB_BASE_ID,\ncast('' as STRING) as DATA_CLCT_DEF_FOIL_LBL_ID,\ncast('' as STRING) as DATA_CLCT_DEF_PLC_VER_ID,\ncast('' as STRING) as DATA_CLCT_DEF_PLC_VERS_BASE_ID,\ncast('' as STRING) as DATA_CLCT_DEF_PLCDHR_BASE_ID,\ncast('' as STRING) as DATA_CLCT_DEF_PLCDHR_ID,\ncast('' as STRING) as DATA_CLCT_DEF_POST_HYD_BASE_ID,\ncast('' as STRING) as DATA_CLCT_DEF_POST_HYD_ID,\ncast('' as STRING) as ENGR_CHG_ORDR_NUM,\ncast('' as STRING) as ERP_RTE_BASE_ID,\ncast('' as STRING) as ERP_RTE_ID,\ncast('' as STRING) as EXCLV_MSTR_LOT_CKLST_ID,\ncast('' as STRING) as FST_STEP_ID,\ncast('' as STRING) as FOIL_OPR_ID,\ncast('' as BOOLEAN) as GSL_WRKF_IND,\ncast('' as STRING) as ICON_ID,\ncast('' as STRING) as IMG_TXT,\ncast('' as BOOLEAN) as IS_EXCLV_CHK_IND,\ncast('' as BOOLEAN) as IS_FRZN_IND,\ncast('' as STRING) as LAST_IN_PRCS_STEP_CKLST_ID,\ncast('' as STRING) as LOC_RTN_FROM_DSTN_TXT,\ncast('' as STRING) as NOTES_TXT,\ncast('' as STRING) as OBJ_TYPE_ID,\ncast('' as STRING) as PROD_CONV_MULTI_STEP_NM,\ncast('' as STRING) as RVSN_ID,\ncast('' as STRING) as RWRK_STEP_NM,\ncast('' as STRING) as SPLT_LOT_INTRO_HS_STEP_ID,\ncast('' as STRING) as SPLT_LOT_INTRO_STEP_NM,\ncast('' as STRING) as SPLT_MOVE_TO_SPEC_ID,\ncast('' as STRING) as STS_CD,\ncast('' as DECIMAL(18,4)) as TOT_CYC_TIME_QTY,\ncast('' as DECIMAL(18,4)) as TOT_YLD_QTY,\ncast('' as STRING) as WIP_MSG_DEF_MGR_ID,\ncast('' as STRING) as WRKF_DESC,\ncast('' as INT) as DAI_ETL_ID,\ncast('' as TIMESTAMP) as DAI_CRT_DTTM,\ncast('' as TIMESTAMP) as DAI_UPDT_DTTM,\ncast('' as timestamp) as _l0_upt_,\n cast('' as timestamp) as _l1_upt_,\n cast('' as string) as _pk_md5_,\n cast('' as string) as _pk_ \n limit 0"
    )

    return df1
